# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rojojo - software products for humans.
email: ben@rojojo.com.au
description: > # this means to ignore newlines until "baseurl:"
  Rojojo is a software products company based out of the Central Coast of NSW, Australia. We focus on building products that help people accomplish their goals.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rojojo.com.au" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
